import Link from 'next/link';
import StarterDashboard from '@/components/starter-dashboard';
import { ArrowUpRight, AudioLines, Check, ChevronDown, Flame, LockKeyhole, MessageCircle, Sparkles, Target } from 'lucide-react';
import { requireProfile } from '@/lib/auth';
import type { Stage, Session, Mistake, Message } from '@/lib/types';
import { CEFR_LABELS } from '@/lib/constants';
import CorrectionCard from '@/components/correction-card';
export const metadata = { title: 'Your space' };
export default async function Dashboard() {
  const { supabase, profile, user } = await requireProfile();
  if (!profile.onboarding_complete) {
    const { data: firstSession, error } = await supabase.from('conversation_sessions').select('id').eq('user_id', user.id).eq('mode', 'onboarding').is('ended_at', null).maybeSingle();
    if (error) throw new Error('Your first conversation could not be loaded. Please try again.');
    const progress = firstSession ? await supabase.from('messages').select('id', { count: 'exact', head: true }).eq('session_id', firstSession.id).eq('role', 'user') : { count: 0, error: null };
    if (progress.error) throw new Error('Your conversation progress could not be loaded.');
    return <StarterDashboard profile={profile} turns={progress.count ?? 0} started={!!firstSession}/>;
  }
  const [stagesResult, sessionsResult, mistakesResult, completedResult] = await Promise.all([
    supabase.from('roadmap_stages').select('*').eq('user_id', user.id).order('stage_number'),
    supabase.from('conversation_sessions').select('*').eq('user_id', user.id).eq('mode', 'practice').order('started_at', { ascending: false }).limit(8),
    supabase.from('mistakes').select('*').eq('user_id', user.id).order('created_at', { ascending: false }).limit(20),
    supabase.from('conversation_sessions').select('stage_id').eq('user_id', user.id).eq('counted', true),
  ]);
  if (stagesResult.error || sessionsResult.error || mistakesResult.error || completedResult.error) throw new Error('Your progress could not be loaded.');
  const stages = stagesResult.data as Stage[]; const sessions = sessionsResult.data as Session[]; const mistakes = mistakesResult.data as Mistake[];
  const recentIds = sessions.map(s => s.id);
  const transcriptResult = recentIds.length ? await supabase.from('messages').select('id,session_id,user_id,role,content,created_at,sequence').in('session_id', recentIds).order('sequence') : { data: [], error: null };
  if (transcriptResult.error) throw new Error('Your recent transcripts could not be loaded.');
  const transcripts = transcriptResult.data as Message[];
  const active = stages.find(s => s.status === 'active') || stages.at(-1);
  const finished = stages.filter(s => s.status === 'completed').length;
  const currentSessions = completedResult.data.filter(s => s.stage_id === active?.id).length;
  const lastDay = profile.last_active_at ? Date.parse(profile.last_active_at.slice(0, 10)) : 0;
  const today = Date.parse(new Date().toISOString().slice(0, 10));
  const streak = today - lastDay <= 86400000 ? profile.streak_count : 0;
  return <main id="main" className="workspace dashboard"><header className="workspace-heading"><div><span className="eyebrow">YOUR SPACE TO GROW</span><h1>Hey, {profile.full_name.split(' ')[0] || 'you'}<span className="hello-spark">✳</span></h1><p>Small conversations. Bigger possibilities.</p></div><span className="level-pill"><span/>{profile.current_cefr_level} · {CEFR_LABELS[profile.current_cefr_level]}</span></header><div className="dashboard-grid"><section className="practice-invite"><div><span className="eyebrow">{finished === 6 ? 'YOUR NEXT CONVERSATION' : `STAGE ${profile.current_stage_number} · YOUR CURRENT FOCUS`}</span><h2>{active?.title || 'Keep the conversation going.'}</h2><p>{active?.description || 'Make a little time for your English today.'}</p><Link href="/practice" className="button">{sessions.some(s => !s.ended_at) ? 'Pick up where you left off' : 'Let’s have a conversation'}<ArrowUpRight size={20}/></Link><span className="invite-note">A few minutes. A little more confidence.</span></div><div className="invite-wave" aria-hidden="true"><AudioLines size={105} strokeWidth={1}/></div></section><section className="stats-stack" aria-label="Your progress"><div><span className="stat-icon"><Flame size={23}/></span><div><strong>{streak}<small> day{streak === 1 ? '' : 's'}</small></strong><span>Current streak · UTC days</span></div></div><div><span className="stat-icon"><MessageCircle size={23}/></span><div><strong>{profile.total_sessions}</strong><span>Conversations completed</span></div></div><div><span className="stat-icon"><Target size={23}/></span><div><strong>{finished}<small> / 6</small></strong><span>Stages completed</span></div></div></section></div>
    <section className="roadmap-section"><div className="block-heading"><div><span className="eyebrow">BUILT AROUND YOU</span><h2>Your way forward.</h2></div><span className="muted">{finished === 6 ? 'Your roadmap is complete. Keep practicing.' : `${Math.min(currentSessions, active?.sessions_required || 3)} of ${active?.sessions_required || 3} sessions in this stage`}</span></div><p className="goal-caption"><Target size={16}/>{profile.learning_goal}</p><ol className="roadmap">{stages.map(stage => { const count = completedResult.data.filter(s => s.stage_id === stage.id).length; return <li key={stage.id} className={`roadmap-stage ${stage.status}`}><span className="stage-badge">{stage.status === 'completed' ? <Check size={19}/> : stage.status === 'locked' ? <LockKeyhole size={16}/> : stage.stage_number}</span><div className="stage-body"><div className="stage-title"><div><span className="eyebrow">STAGE {stage.stage_number} · {stage.cefr_level}</span><h3>{stage.title}</h3></div><span className={`status-tag ${stage.status}`}>{stage.status === 'active' ? 'You are here' : stage.status === 'completed' ? 'Completed' : 'Up next'}</span></div><p>{stage.description}</p><div className="skill-tags">{stage.focus_skills.map(skill => <span key={skill}>{skill}</span>)}</div>{stage.status === 'active' && <div className="stage-progress"><div><span style={{ width: `${Math.min(count / stage.sessions_required, 1) * 100}%` }}/></div><small>{count}/{stage.sessions_required} conversations</small></div>}</div></li>; })}</ol><p className="helper-text">Complete three conversations with at least four of your own turns to unlock the next stage. Your CEFR estimate stays provisional; stage completion tracks practice, not certification.</p></section>
    <div className="review-grid"><section><div className="block-heading"><h2>Little things to take with you.</h2><Sparkles size={20}/></div><p className="muted section-description">Your latest gentle corrections, saved for another look.</p>{mistakes.length ? <div className="correction-list">{mistakes.map(m => <CorrectionCard key={m.id} mistake={m}/>)}</div> : <div className="empty-state"><Sparkles size={28}/><h3>Room to learn.</h3><p>Useful corrections from your conversations will land right here.</p></div>}</section><section><div className="block-heading"><h2>Conversations that count.</h2><MessageCircle size={20}/></div><p className="muted section-description">Pick up a thought. Revisit a moment.</p>{sessions.length ? <div className="session-list">{sessions.map(session => <details key={session.id} className="session-card"><summary><span><strong>{session.topic}</strong><small>{new Date(session.started_at).toLocaleDateString('en', { day: 'numeric', month: 'short', timeZone: 'UTC' })} · {session.ended_at ? session.counted ? 'Completed' : 'Short practice' : 'In progress'}{session.session_score != null && ` · ${session.session_score}/100`}</small></span><ChevronDown size={17}/></summary><p>{session.summary || 'Your conversation is saved. Continue whenever you’re ready.'}</p>{!session.ended_at && <Link className="text-link" href="/practice">Continue conversation <ArrowUpRight size={16}/></Link>}<div className="saved-transcript">{transcripts.filter(m => m.session_id === session.id).map(m => <div key={m.id}><strong>{m.role === 'user' ? 'You' : 'Vashu'}</strong><p>{m.content}</p></div>)}</div></details>)}</div> : <div className="empty-state"><AudioLines size={30}/><h3>Your story starts now.</h3><p>Your conversations and reflections will be saved here.</p><Link href="/practice" className="text-link">Start a conversation <ArrowUpRight size={16}/></Link></div>}</section></div>
  </main>;
}
