'use client';
import Link from 'next/link';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { ArrowUpRight, AudioLines, Check, ChevronDown, Globe2, Menu, Mic, MoveUpRight, Sparkles, X } from 'lucide-react';
import { Logo, Waveform } from './brand';

const goals = ['Everyday conversations', 'Job interviews', 'Studying abroad', 'Speaking with confidence'];
export default function Landing() {
  const [menu, setMenu] = useState(false);
  const [goal, setGoal] = useState(0);
  useEffect(() => {
    const observer = new IntersectionObserver(entries => entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('revealed'); observer.unobserve(e.target); } }), { threshold: 0.12 });
    document.querySelectorAll('[data-reveal]').forEach(el => observer.observe(el));
    return () => observer.disconnect();
  }, []);
  return <div className="landing">
    <header className="landing-nav container"><Logo/><nav className={menu ? 'open' : ''} aria-label="Main navigation"><a href="#how-it-works" onClick={() => setMenu(false)}>How it works</a><a href="#your-path" onClick={() => setMenu(false)}>Your learning path</a><a href="#meet-vashu" onClick={() => setMenu(false)}>Meet Vashu <span className="tiny-tag">YOUR PARTNER</span></a></nav><div className="nav-actions"><Link href="/login" className="login-link">Log in</Link><Link href="/signup" className="button button-small">Let’s talk <ArrowUpRight size={17}/></Link><button className="mobile-menu icon-button" onClick={() => setMenu(!menu)} aria-label={menu ? 'Close menu' : 'Open menu'} aria-expanded={menu}>{menu ? <X/> : <Menu/>}</button></div></header>
    <main id="main">
      <section className="hero container">
        <div className="hero-copy"><div className="eyebrow"><span className="spark-icon">✳</span> A LITTLE PRACTICE. A LOT MORE YOU.</div><h1>Your thoughts.<br/>Your words.<br/><span>Your confidence.</span></h1><p>English is already in you. Let’s bring it out.<br className="desktop-break"/> Talk, make mistakes, and find your flow with a<br className="desktop-break"/> voice partner who gets you.</p><div className="hero-cta"><Link className="button button-large" href="/signup">Find your speaking voice <ArrowUpRight size={21}/></Link><span>No pressure. Just a conversation.</span></div><div className="hero-footnote"><span className="mini-wave"><AudioLines size={19}/></span><span>Made for real life.<br/><strong>And the way you actually speak.</strong></span></div></div>
        <div className="hero-visual" aria-label="An expressive voice orb with sample conversation"><div className="orb-stage"><div className="orb-halo"/><Image className="orb-art" src="/voice-orb.png" alt="A luminous green glass orb, rippling like the sound of a voice" width={1024} height={1024} priority/></div><div className="visual-label"><span className="live-dot"/> YOUR NEXT CHAPTER SOUNDS LIKE YOU</div><div className="floating-label"><Sparkles size={15}/> A friend. A little nudge. A new you.</div><div className="conversation-preview"><div className="preview-head"><span className="vashu-avatar"><AudioLines size={20}/></span><div><strong>Vashu</strong><span>Your English practice partner</span></div><span className="preview-status">Let’s talk</span></div><p>“Tell me about that one thing you<br className="desktop-break"/> could talk about for hours.”</p><div className="preview-bottom"><Waveform/><span className="preview-mic"><Mic size={18}/></span></div></div><div className="orb-caption"><span>LESS OVERTHINKING.</span><span>MORE SPEAKING. <MoveUpRight size={14}/></span></div></div>
      </section>
      <section className="belief-strip"><div className="container"><span>Big dreams start with<br/><strong>small conversations.</strong></span><div><Globe2/><span>Your accent.<br/><strong>Your advantage.</strong></span></div><div><Mic/><span>A judgment-free space.<br/><strong>Every single day.</strong></span></div><div><Sparkles/><span>A path that’s personal.<br/><strong>Because you are.</strong></span></div></div></section>
      <section id="how-it-works" className="section container"><div className="section-heading" data-reveal><div><span className="eyebrow">LESS LIKE A LESSON. MORE LIKE LIFE.</span><h2>From “what if I mess up?”<br/>to <span>“let me tell you.”</span></h2></div><p>No scripts to memorize. No perfect answers.<br/>Just you, showing up and speaking up.</p></div><div className="feature-grid"><article className="feature-card" data-reveal><div className="feature-number">01 <ArrowUpRight/></div><div className="mini-chat"><span>So, what brings you here?</span><span>I want to feel more confident.</span><span>That’s a great place to start.</span></div><h3>Start with a hello.</h3><p>A short voice chat helps Vashu understand your English, your goals, and what makes you, you.</p></article><article className="feature-card feature-lime" data-reveal><div className="feature-number">02 <AudioLines/></div><div className="correction-example"><span>“Yesterday I go to a café.”</span><strong><Check size={17}/> “Yesterday I went to a café.”</strong><small>Small adjustment. Big difference.</small></div><h3>Find your rhythm.</h3><p>Talk about real things. Get a gentle correction when it helps, then keep the conversation going.</p></article><article className="feature-card" data-reveal><div className="feature-number">03 <Sparkles/></div><div className="growth-bars" aria-label="Illustrative progress"><i/><i/><i/><i/><i/><span>You, a little more confident ↗</span></div><h3>Hear yourself grow.</h3><p>A personal six-stage roadmap turns everyday practice into progress you can actually feel.</p></article></div></section>
      <section id="your-path" className="path-section container" data-reveal><div className="path-intro"><span className="eyebrow">YOUR LIFE. YOUR ENGLISH.</span><h2>Where do you<br/>want your words<br/>to take you?</h2><p>Whatever’s next, we’ll help you say it.<br/>Your roadmap starts with your reason.</p><Link href="/signup" className="text-link">Build my learning path <ArrowUpRight size={20}/></Link></div><div className="goal-list">{goals.map((item, i) => <button key={item} onClick={() => setGoal(i)} className={goal === i ? 'selected' : ''} aria-pressed={goal === i}><span className="goal-index">0{i + 1}</span><span>{item}</span><ArrowUpRight size={22}/></button>)}<p>{['Tell stories, make small talk, and feel at home in everyday English.', 'Explain your experience and answer follow-up questions with clarity.', 'Join the discussion, meet new people, and make yourself understood.', 'Turn the words in your head into a voice you feel good about.'][goal]}</p></div></section>
      <section id="meet-vashu" className="meet-section container" data-reveal><div className="meet-art"><div className="meet-symbol"><AudioLines strokeWidth={1} size={105}/></div><span>A GOOD LISTENER.<br/>AN EVEN BETTER PRACTICE PARTNER.</span></div><div><span className="eyebrow">MEET YOUR VOICE PARTNER</span><h2>A little less tutor.<br/>A little more <span>Vashu.</span></h2><p>Someone to talk to, not perform for. Vashu remembers what you’re working on, meets you at your level, and gives you space to get there.</p><p>Pick a voice you like. Set your own pace.<br/>Then, just be yourself.</p><Link href="/signup" className="button">Say hello to Vashu <ArrowUpRight size={19}/></Link></div></section>
      <section className="faq-section container" data-reveal><h2>A few things<br/>you might be wondering.</h2><div>{[['Do I need to be good at English already?', 'Not at all. Your first conversation helps Vashu find your starting point, from beginner to advanced. You can pause, take your time, and try again.'], ['Will Vashu correct every mistake?', 'No. Vashu focuses on one or two useful corrections at a time, so you can keep talking. You can revisit those corrections after your conversation.'], ['Is my microphone always on?', 'Only when you start recording. Tap again to send your voice message. The microphone stops between turns. Audio is sent for transcription; Spoklet saves the conversation text, not your recording.'], ['How does my learning path work?', 'Your first conversation creates six stages around your goals. Complete three practice sessions with at least four of your own turns in each to unlock the next stage.']].map(([q, a]) => <details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</div></section>
      <section className="final-cta container" data-reveal><span className="eyebrow">YOU DON’T NEED PERFECT ENGLISH TO START.</span><h2>You just need<br/>your first <span>hello.</span></h2><Link href="/signup" className="button button-large">Let’s hear it <ArrowUpRight size={22}/></Link><div className="cta-asterisk" aria-hidden="true">✳</div></section>
    </main><footer className="footer container"><Logo/><span>A little more English. A lot more you.</span><span>© {new Date().getFullYear()} Spoklet</span></footer>
  </div>;
}
