import Link from 'next/link';
import { ArrowUpRight, Check, ChevronDown, Compass, MessageCircle, Sparkles } from 'lucide-react';
import type { Profile } from '@/lib/types';
import { supportLanguage } from '@/lib/language';
const stages = [
  { title: 'अपना परिचय', english: 'Introduce yourself', description: 'अपना नाम और अपने बारे में एक बात कहें। छोटे वाक्यों से शुरुआत करें।', detail: 'Start with your name and one thing about yourself. Build a few comfortable sentences.', example: 'My name is ___. I live in ___.', skills: 'I am · I live · I like' },
  { title: 'हर दिन की बातें', english: 'Talk about your day', description: 'अपनी सुबह, काम और पसंद के बारे में बात करें।', detail: 'Describe your morning, work, and things you enjoy.', example: 'I drink tea every morning.', skills: 'Daily routines · Present tense' },
  { title: 'पूछें और जवाब दें', english: 'Ask and answer', description: 'दुकान, रास्ते या रोज़ की बातचीत में छोटे सवाल पूछें।', detail: 'Ask short questions in a shop, on the street, or in everyday conversations.', example: 'Could you help me, please?', skills: 'Questions · Polite requests' },
  { title: 'अपनी कहानी कहें', english: 'Tell a little story', description: 'कल क्या हुआ और आगे क्या करना है, धीरे-धीरे बताएं।', detail: 'Share something that happened yesterday and something you plan to do.', example: 'Yesterday, I visited a friend.', skills: 'Past events · Future plans' },
  { title: 'आपका अपना लक्ष्य', english: 'Practise your real life', description: 'आपके लक्ष्य के हिसाब से काम, travel या दोस्तों से बातचीत की practice करें।', detail: 'Practise situations that match your goal: work, travel, or conversations with friends.', example: 'Let me tell you about my work.', skills: 'Role play · Useful vocabulary' },
  { title: 'थोड़ा और आत्मविश्वास', english: 'Keep the conversation going', description: 'अपनी राय बताएं, अगला सवाल पूछें और अटकने पर दोबारा कोशिश करें।', detail: 'Share an opinion, ask a follow-up question, and try again when you get stuck.', example: 'I think… What do you think?', skills: 'Opinions · Follow-up questions' },
];
export default function StarterDashboard({ profile, turns, started }: { profile: Profile; turns: number; started: boolean }) {
  const english = supportLanguage(profile.support_language) === 'english';
  return <main id="main" className="workspace starter-dashboard">
    <header className="workspace-heading"><div><span className="eyebrow">YOUR LEARNING ROADMAP</span><h1>{english ? 'Your English journey starts here.' : 'छोटे कदम। आपकी अपनी English.'}</h1><p>{english ? 'Explore your path, then let Vashu shape it around you.' : 'हिंदी या Hinglish में बात करें। English हम साथ में सीखेंगे।'}</p></div><span className="level-pill"><Compass size={16}/>Starter preview</span></header>
    <section className="starter-invite"><div><span className="eyebrow">LET’S MAKE THIS YOURS</span><h2>{english ? 'Meet Vashu, at your pace.' : 'पहले थोड़ी जान-पहचान।'}</h2><p>{english ? 'Four short replies help Vashu understand your goal and create your personal roadmap. Hindi answers and typing are welcome.' : 'चार छोटे जवाबों से Vashu आपका लक्ष्य समझकर personal roadmap बनाएगा। हिंदी में बोलें या लिखें — दोनों ठीक हैं।'}</p><Link className="button" href="/onboarding">{english ? started ? 'Continue with Vashu' : 'Meet Vashu' : started ? 'बातचीत जारी रखें' : 'Vashu से मिलें'}<ArrowUpRight size={19}/></Link></div>
      <div className="starter-progress"><MessageCircle size={27}/><strong>{Math.min(turns, 4)}<small> / 4</small></strong><span>{english ? 'replies toward your personal plan' : 'जवाब · आपके personal plan के लिए'}</span><div className="progress-dots" aria-label={`${Math.min(turns, 4)} of 4 replies`}>{[1, 2, 3, 4].map(n => <span key={n} className={turns >= n ? 'complete' : ''}>{turns >= n ? <Check size={15}/> : n}</span>)}</div>{turns >= 4 && <p>{english ? 'Ready to build your roadmap. Continue your conversation.' : 'अब roadmap बन सकता है। बातचीत खोलें।'}</p>}</div>
    </section>
    <section className="roadmap-section"><div className="block-heading"><div><span className="eyebrow">SIX SMALL STEPS</span><h2>{english ? 'A first look at your path.' : 'आपका रास्ता, एक नज़र में।'}</h2></div><span className="muted">{english ? 'Tap a step to explore' : 'कोई भी step खोलकर देखें'}</span></div><p className="starter-disclaimer"><Sparkles size={16}/>{english ? 'This is a starter preview, not an assessment. Your conversation will replace it with six stages tailored to you.' : 'यह शुरुआती preview है, आपका assessment नहीं। बातचीत के बाद आपके लक्ष्य के हिसाब से छह नए stages मिलेंगे।'}</p>
      <div className="starter-stages">{stages.map((stage, index) => <details key={stage.english} className="starter-step" open={index === 0}><summary><span className="starter-number">{String(index + 1).padStart(2, '0')}</span><span><strong>{english ? stage.english : stage.title}</strong><small>{english ? stage.skills : stage.english}</small></span><ChevronDown size={19}/></summary><div><p>{english ? stage.detail : stage.description}</p><blockquote>{stage.example}</blockquote><span className="helper-text">{stage.skills}</span></div></details>)}</div>
    </section>
    <p className="starter-footer">{english ? 'Your conversation saves as you go. You can visit Settings or log out at any time.' : 'बातचीत अपने आप save होती रहती है। Settings खोलें या कभी भी logout करें।'} <Link href="/settings">{english ? 'Choose voice & language' : 'आवाज़ और भाषा चुनें'}<ArrowUpRight size={14}/></Link></p>
  </main>;
}
